### PR TITLE
Move to flot 4.2.1

### LINKED ISSUE #4: Upgrade to flot 4.2.1?
There's [some dicussion over on criterion](https://github.com/bos/criterion/issues/213#issuecomment-717352722) about the log-axis support in newer versions of flot. How would you feel about updating js-flot to a newer version? I'd be happy to make a PR for it here and fix up criterion, but it would mean somebody would need to update hoogle and shake.

### PR DESCRIPTION
**Pull request by jonascarpay**
Fixes #4 

This PR upgrades to flot 4.2.1. However, we've been trying to port criterion and generally found 4.2.1 to be much more annoying and finicky than 0.8.3, [so we gave up instead ended up trying out `chart.js`](https://github.com/bos/criterion/issues/213#issuecomment-722538968). In general, I'm not entirely sure what's up with flot at this point. It seems that at some point someone did a big fork called [engineering-flot](https://github.com/ni-kismet/engineering-flot), which was then merged into flot proper, but none of the major CDN's followed suit.

So, I'm not sure if you should actually merge this, but I'm opening this PR because I feel it would be strange for me to make that choice for you. Maybe we should just leave it open until there is some reason to merge it, and hopefully criterion will have switched to `chart.js` at that point?

### CODE REVIEW

**Comment by ndmitchell** [comment]
Thanks for the PR and investigations.

Yuk. I guess it seems to make sense for people to move to chart.js then. Would be good for someone to create a similar js-chart package, so that Haskell packages depending on it can get a distro-compliant source.

My inclination is to also freeze this package at the version its on, if its unlikely a new version would be of benefit to anyone.

**Comment by ndmitchell** [comment]
Thanks for updating the PR. So I don't think hijacking this repo to be js-chart is a good idea - we should preserve this for the js-flot package as long as it remains a thing (which is probably forever). Instead, we should create a new js-chart package and repo. For that, the options are either of:

1. We just use https://github.com/jonascarpay/js-chart as the upstream source forever, freezing this repo, and you become the primary maintainer of js-chart. I may well switch to js-chart, and might contribute to it, but its yours to do with as you wish. You might want to stop using my CI scripts, so you can have more control over the package, but that's entirely your choice.
2. I fork your repo to ndmitchell/js-chart, review the changes, make a release. I'm primary maintainer, although you'd be welcome to be a secondary maintainer etc. in Hackage.

I'm perfectly happy with either of those, with a slight preference towards the first, since its fractionally less effort to me, but it is pretty fractional so I'm not too fussed either way.

**Comment by jonascarpay** [comment]
Oops, sorry, I didn't realize I was changing this PR! I was using `js-flot` as a base since it's functionally the same, I didn't mean to actually suggest that this repo become the new `js-chart`. Sorry for the confusion! I'm essentially doing option 1, `js-chart` should be up on hackage/stackage soon.

I'm closing this PR. For posterity, if anybody comes across this and _does_ want a `js-flot` for 4.2.1, you can find it here: https://github.com/jonascarpay/js-chart/tree/js-flot_4.2.1

**Comment by ndmitchell** [comment]
Hehe, no worries - so are you planning to make and release a js-chart? I would be very keen to consider using such a thing.

**Comment by jonascarpay** [comment]
[Yeah](https://github.com/jonascarpay/js-chart/tree/master), I'd like to depend on it for https://github.com/bos/criterion/pull/229/. Travis is a bit congested, but I'm pushing to {h,st}ackage as soon as it's green.

**Comment by ndmitchell** [comment]
Great to see its up now - I've adjusted the readme of this repo to point people towards that. This repo is now mostly stale.

**Pull request closed without merging**
